import { SampleDocument } from '../types/api';

export const SAMPLES: SampleDocument[] = [
  { id: 'sample1-pdf', title: 'Standard Experience Letter (PDF)', filename: 'sample1_standard.pdf', description: 'A well-formatted PDF experience letter with all required fields present.', expected_type: 'Experience Letter', raw_text: '' },
  { id: 'sample1-docx', title: 'Standard Experience Letter (DOCX)', filename: 'sample1_standard.docx', description: 'The same complete experience letter in an editable document.', expected_type: 'Experience Letter', raw_text: '' },
  { id: 'sample2-pdf', title: 'Different Writing Style', filename: 'sample2_different_style.pdf', description: 'An experience certificate using alternate phrasing and layout.', expected_type: 'Experience Certificate', raw_text: '' },
  { id: 'sample3-txt', title: 'Missing Information', filename: 'sample3.txt', description: 'A letter with several fields absent, testing validation warnings and failures.', expected_type: 'Experience Letter (Incomplete)', raw_text: '' },
  { id: 'sample4-pdf', title: 'Alternate Wording Certificate', filename: 'sample4_alternate.pdf', description: "Uses 'we certify', 'employed from', and 'held the position of' phrasing.", expected_type: 'Experience Certificate', raw_text: '' },
  { id: 'sample5-pdf', title: 'Incomplete PDF Letter', filename: 'sample5_incomplete.pdf', description: 'A PDF with real employee, company, role, and duration but missing dates and signatory.', expected_type: 'Experience Letter (Incomplete)', raw_text: '' },
  { id: 'sample6-pdf', title: 'Employment Certificate', filename: 'sample6_certificate.pdf', description: "A complete certificate using 'worked with our organization' and 'served as' wording.", expected_type: 'Experience Certificate', raw_text: '' },
  { id: 'sample7-many-dates', title: 'Many Dates Experience Letter', filename: 'sample7_many_dates.pdf', description: 'A three-page letter with appraisal, promotion, project, leave, and issue dates.', expected_type: 'Experience Letter', raw_text: '' },
  { id: 'sample8-many-dates-certificate', title: 'Many Dates Employment Certificate', filename: 'sample8_many_dates_certificate.pdf', description: 'A three-page certificate with multiple historical and employment dates.', expected_type: 'Experience Certificate', raw_text: '' },
  { id: 'sample9-multiple-periods', title: 'Multiple Employment Periods', filename: 'sample9_multiple_periods.pdf', description: 'Two separate employment periods at the same company.', expected_type: 'Experience Letter', raw_text: '' },
  { id: 'sample10-current-employee', title: 'Current Employee', filename: 'sample10_current_employee.pdf', description: 'An active employee with no last working date.', expected_type: 'Experience Letter', raw_text: '' },
  { id: 'sample11-conflicting-dates', title: 'Conflicting Dates', filename: 'sample11_conflicting_dates.pdf', description: 'Conflicting separation dates that should require review.', expected_type: 'Experience Letter', raw_text: '' },
  { id: 'sample12-promotion-history', title: 'Promotion History', filename: 'sample12_promotion_history.pdf', description: 'Multiple designations and promotion dates.', expected_type: 'Experience Certificate', raw_text: '' },
  { id: 'sample13-labeled-fields', title: 'Labeled Fields', filename: 'sample13_labeled_fields.pdf', description: 'Structured labels for every extracted field.', expected_type: 'Experience Letter', raw_text: '' },
  { id: 'sample14-header-footer-noise', title: 'Header and Footer Noise', filename: 'sample14_header_footer_noise.pdf', description: 'Repeated headers, footers, reviews, and compliance dates.', expected_type: 'Experience Letter', raw_text: '' },
  { id: 'sample15-multiple-companies', title: 'Multiple Companies', filename: 'sample15_multiple_companies.pdf', description: 'Career history with more than one employer.', expected_type: 'Experience Certificate', raw_text: '' },
  { id: 'sample16-missing-dates', title: 'Missing Dates', filename: 'sample16_missing_dates.pdf', description: 'Real identity and role but no explicit employment dates.', expected_type: 'Experience Letter', raw_text: '' },
  { id: 'sample17-locale-dates', title: 'Numeric Locale Dates', filename: 'sample17_locale_dates.pdf', description: 'Numeric day/month dates requiring locale-aware parsing.', expected_type: 'Experience Certificate', raw_text: '' },
  { id: 'sample18-duplicate-headers', title: 'Duplicate Headers', filename: 'sample18_duplicate_headers.pdf', description: 'Repeated page headers around the employment details.', expected_type: 'Experience Letter', raw_text: '' },
];
